Storage/Controllers/ProductController.cs
using Storage.Context;
using Storage.Models;
using Storage.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Storage.Controllers
{
    public class ProductController : Controller
    {
        private StorageContext _db;

        public ProductController()
        {
            _db = new StorageContext();
        }

        // GET: Storage
        public ActionResult Index()
        {
            return View(_db.Products.Include(path => path.ProductType).ToList());
        }

        public ActionResult AjaxDemo()
        {
            return View();
        }

        public ActionResult _index()
        {
            List<Product> products = new List<Product>();
            products = _db.Products.ToList();
                       
            return PartialView(products);
        }

        public ActionResult _delete(int id)
        {
            Product product = _db.Products.Find(id);
            _db.Products.Remove(product);
            _db.SaveChanges();

            List<Product> products = new List<Product>();
            products = _db.Products.ToList();
            return PartialView("_index", products);
        }

        // GET: Storage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Product product = _db.Products.Find(id);

            var product = _db.Products.Include(path => path.ProductType).Where(p => p.Id == @id).FirstOrDefault<Product>();
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Storage/Create
        public ActionResult Create()
        {
            var productCreateViewModel = new ProductProductTypeViewModel();
            var productType = _db.ProductTypes.ToList();
            productCreateViewModel.ProductTypes = productType;
            return View(productCreateViewModel);
        }

        // POST: Storage/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductProductTypeViewModel pp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Products.Add(pp.Product);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }

                //fill productypes for re-displaying create form when fail
                pp.ProductTypes = _db.ProductTypes.ToList();
                return View(pp);
            }
            catch
            {
                return View();
            }
        }

        // GET: Storage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var productProductTypeViewModel = new ProductProductTypeViewModel();
            var product = _db.Products.Find(id);
            var productType = _db.ProductTypes.ToList();
            productProductTypeViewModel.Product = product;
            productProductTypeViewModel.ProductTypes = productType;

            if (product == null)
            {
                return HttpNotFound();
            }
            return View(productProductTypeViewModel);
        }

        // POST: Storage/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductProductTypeViewModel pp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(pp.Product).State = System.Data.Entity.EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                //fill productypes for re-displaying edit form when fail
                pp.ProductTypes = _db.ProductTypes.ToList();
                return View(pp);
            }
            catch
            {
                return View();
            }
        }

        // GET: Storage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Product product = _db.Products.Find(id);
            var product = _db.Products.Include(path => path.ProductType).Where(p => p.Id == @id).FirstOrDefault<Product>();
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Storage/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Product product)
        {
            //TODO: to be researched further more
            try
            {
                Product p = new Product();
                //if (ModelState.IsValid)
                //{
                    p = _db.Products.Find(product.Id);
                    if (p == null)
                    {
                        return HttpNotFound();
                    }
                    _db.Products.Remove(p);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                //}
                //return View(p);
            }
            catch
            {
                return View();
            }
        }
    }
}

Storage/Controllers/ProductTypeController.cs
using Storage.Context;
using Storage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Storage.Controllers
{
    public class ProductTypeController : Controller
    {
        private StorageContext _db;

        public ProductTypeController()
        {
            _db = new StorageContext();
        }

        // GET: ProductType
        public ActionResult Index()
        {
            return View(_db.ProductTypes.ToList());
        }

        // GET: ProductType/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductType productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return HttpNotFound();
            }
            return View(productType);
        }

        // GET: ProductType/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductType/Create
        [HttpPost]
        public ActionResult Create(ProductType productType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.ProductTypes.Add(productType);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(productType);
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductType/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductType productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return HttpNotFound();
            }
            return View(productType);
        }

        // POST: ProductType/Edit/5
        [HttpPost]
        public ActionResult Edit(ProductType productType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(productType).State = System.Data.Entity.EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(productType);
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductType/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductType productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return HttpNotFound();
            }
            return View(productType);
        }

        // POST: ProductType/Delete/5
        [HttpPost]
        public ActionResult Delete(ProductType productType)
        {
            try
            {
                ProductType p = new ProductType();
                if (ModelState.IsValid)
                {
                    p = _db.ProductTypes.Find(productType.Id);
                    if (p == null)
                    {
                        return HttpNotFound();
                    }
                    _db.ProductTypes.Remove(p);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(p);
            }
            catch
            {
                return View();
            }
        }
    }
}

Storage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Products", "Index", "Product", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Product Types", "Index", "ProductType", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Ajax Demo", "AjaxDemo", "Product", null, new { @class = "nav-link" })
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>